# Generated by Django 5.2.6 on 2025-12-26 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItikafProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('registration_deadline', models.DateTimeField()),
                ('location', models.CharField(default='Main Prayer Hall', max_length=200)),
                ('capacity', models.PositiveIntegerField()),
                ('gender_restriction', models.CharField(choices=[('male', 'Male Only'), ('female', 'Female Only'), ('both', 'Both')], default='both', max_length=10)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_free', models.BooleanField(default=True)),
                ('requirements', models.TextField(blank=True, help_text='Requirements for participants')),
                ('what_to_bring', models.TextField(blank=True, help_text='What participants should bring')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='itikaf/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_itikaf_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Iʿtikāf Program',
                'verbose_name_plural': 'Iʿtikāf Programs',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ItikafRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=200)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('special_requirements', models.TextField(blank=True, help_text='Dietary restrictions, medical needs, etc.')),
                ('notes', models.TextField(blank=True, help_text='Additional notes from participant')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('payment_method', models.CharField(choices=[('card', 'Credit Card (Chapa)'), ('manual_qr', 'Manual Transfer / QR Code'), ('cash', 'Cash (On Arrival)')], default='cash', max_length=20)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='itikaf/proofs/')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='itikaf.itikafprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itikaf_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Iʿtikāf Registration',
                'verbose_name_plural': 'Iʿtikāf Registrations',
                'ordering': ['-registered_at'],
                'unique_together': {('program', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ItikafSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_number', models.PositiveIntegerField(help_text='Day number in the program (1, 2, 3, etc.)')),
                ('fajr_activity', models.CharField(blank=True, default='Fajr Prayer', max_length=200)),
                ('dhuhr_activity', models.CharField(blank=True, default='Dhuhr Prayer', max_length=200)),
                ('asr_activity', models.CharField(blank=True, default='Asr Prayer', max_length=200)),
                ('maghrib_activity', models.CharField(blank=True, default='Maghrib Prayer', max_length=200)),
                ('isha_activity', models.CharField(blank=True, default='Isha Prayer', max_length=200)),
                ('morning_session', models.TextField(blank=True, help_text='Morning session activities')),
                ('afternoon_session', models.TextField(blank=True, help_text='Afternoon session activities')),
                ('evening_session', models.TextField(blank=True, help_text='Evening session activities')),
                ('breakfast_time', models.TimeField(blank=True, null=True)),
                ('lunch_time', models.TimeField(blank=True, null=True)),
                ('dinner_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='itikaf.itikafprogram')),
            ],
            options={
                'verbose_name': 'Iʿtikāf Schedule',
                'verbose_name_plural': 'Iʿtikāf Schedules',
                'ordering': ['date', 'day_number'],
                'unique_together': {('program', 'date')},
            },
        ),
    ]
