# Generated by Django 5.2.6 on 2025-12-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='currency',
            field=models.CharField(default='ETB', max_length=3),
        ),
        migrations.AlterField(
            model_name='donationcause',
            name='currency',
            field=models.CharField(default='ETB', max_length=3),
        ),
    ]
