# Generated by Django 5.2.6 on 2025-12-26 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('imam', models.CharField(help_text='Name of the person giving the ders', max_length=200)),
                ('day_of_week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('time', models.CharField(help_text='e.g. After Asr, 4:00 PM', max_length=100)),
                ('location', models.CharField(default='Main Prayer Hall', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Timetable Entries',
                'ordering': ['day_of_week', 'time'],
            },
        ),
        migrations.CreateModel(
            name='EducationalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('service_type', models.CharField(choices=[('daily_qirat', 'Daily Qirat Program'), ('community_quran', 'Community Quran Reading'), ('friday_khutba', 'Friday Khutba'), ('quran_recitation', 'Quran Recitation (Qirat)'), ('quran_memorization', 'Quran Memorization (Hifz)'), ('arabic_language', 'Arabic Language'), ('islamic_studies', 'Islamic Studies'), ('tajweed', 'Tajweed'), ('fiqh', 'Fiqh (Islamic Jurisprudence)'), ('hadith', 'Hadith Studies'), ('tafseer', 'Tafseer (Quran Interpretation)'), ('ders_program', 'Weekly Ders Program')], max_length=30)),
                ('schedule', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('age_group', models.CharField(choices=[('children', 'Children (6-12)'), ('teens', 'Teens (13-17)'), ('adults', 'Adults (18+)'), ('seniors', 'Seniors (60+)')], max_length=20)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_free', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('full', 'Full'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('schedule', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('age_group', models.CharField(choices=[('children', 'Children (6-12)'), ('teens', 'Teens (13-17)'), ('adults', 'Adults (18+)'), ('seniors', 'Seniors (60+)')], max_length=20)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_free', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('full', 'Full'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taught_courses', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='education.educationalservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('subject', models.CharField(choices=[('quran_recitation', 'Quran Recitation'), ('tafseer', 'Tafseer'), ('hadith', 'Hadith'), ('fiqh', 'Fiqh'), ('seerah', 'Seerah'), ('aqidah', 'Aqidah'), ('general', 'General Lecture')], default='general', max_length=50)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Video URL', null=True)),
                ('video_file', models.FileField(blank=True, help_text='Upload local video file', null=True, upload_to='lectures/videos/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='lectures/audio/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='lectures/thumbnails/')),
                ('date_recorded', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='ServiceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('card', 'Credit Card (Chapa)'), ('manual_qr', 'Manual Transfer / QR Code'), ('cash', 'Cash'), ('free', 'Free / Scholarship')], default='free', max_length=20)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='education/proofs/')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='education.course')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='education.educationalservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('course', 'user'), ('service', 'user')},
            },
        ),
    ]
