# Generated by Django 5.2.6 on 2025-11-15 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('service_type', models.CharField(choices=[('daily_qirat', 'Daily Qirat Program'), ('community_quran', 'Community Quran Reading'), ('friday_khutba', 'Friday Khutba'), ('quran_recitation', 'Quran Recitation (Qirat)'), ('quran_memorization', 'Quran Memorization (Hifz)'), ('arabic_language', 'Arabic Language'), ('islamic_studies', 'Islamic Studies'), ('tajweed', 'Tajweed'), ('fiqh', 'Fiqh (Islamic Jurisprudence)'), ('hadith', 'Hadith Studies'), ('tafseer', 'Tafseer (Quran Interpretation)')], max_length=30)),
                ('schedule', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('age_group', models.CharField(choices=[('children', 'Children (6-12)'), ('teens', 'Teens (13-17)'), ('adults', 'Adults (18+)'), ('seniors', 'Seniors (60+)')], max_length=20)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_free', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('full', 'Full'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='education.educationalservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('service', 'user')},
            },
        ),
    ]
