# Generated by Django 5.2.6 on 2025-12-08 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('subject', models.CharField(choices=[('quran_recitation', 'Quran Recitation'), ('tafseer', 'Tafseer'), ('hadith', 'Hadith'), ('fiqh', 'Fiqh'), ('seerah', 'Seerah'), ('aqidah', 'Aqidah'), ('general', 'General Lecture')], default='general', max_length=50)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Video URL', null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='lectures/audio/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='lectures/thumbnails/')),
                ('date_recorded', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
    ]
