# Generated by Django 5.2.6 on 2025-12-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload local video file', null=True, upload_to='lectures/videos/'),
        ),
    ]
