# Generated by Django 5.2.6 on 2025-12-26 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='donation_cause',
            field=models.ForeignKey(blank=True, help_text='Optional: Link this announcement to a donation cause for fundraising', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='donations.donationcause'),
        ),
    ]
